package com.instavault.app.security

import android.content.Context
import android.util.Log
import com.google.android.play.core.integrity.IntegrityManagerFactory
import com.google.android.play.core.integrity.IntegrityTokenRequest
import com.google.android.play.core.integrity.IntegrityServiceException
import kotlinx.coroutines.tasks.await

/**
 * A highly decoupled Singleton manager to handle Google Play Integrity API requests.
 * This class abstracts away the complexities of interacting with Play Services,
 * making it a true "Plug-and-Play" module that can be injected/called from anywhere.
 */
class PlayIntegrityManager private constructor(context: Context) {

    private val integrityManager = IntegrityManagerFactory.create(context.applicationContext)

    // IMPORTANT: If you verify requests on your own server using a custom Google Cloud Project,
    // specify the project number here. If you rely purely on the Play Console default link, leave it null.
    private val cloudProjectNumber: Long? = 1040039421212L

    companion object {
        @Volatile
        private var INSTANCE: PlayIntegrityManager? = null

        /**
         * Returns the Singleton instance of the PlayIntegrityManager.
         */
        fun getInstance(context: Context): PlayIntegrityManager {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: PlayIntegrityManager(context).also { INSTANCE = it }
            }
        }
    }

    /**
     * Requests a Play Integrity token using the provided nonce.
     * This function is a suspending coroutine and uses `.await()` to map the Play Services Task
     * into a sequential asynchronous flow without messy callbacks.
     * 
     * @param nonce A Base64 URL-safe, non-wrapping string generated by your secure backend.
     * @return AttestationResult containing the token on success, or error details on failure.
     */
    suspend fun requestIntegrityToken(nonce: String): AttestationResult {
        return try {
            Log.d("PlayIntegrity", "Requesting integrity token with nonce...")
            
            val requestBuilder = IntegrityTokenRequest.builder()
                .setNonce(nonce)
                
            // Set Cloud Project Number if required by your GCP Setup
            cloudProjectNumber?.let { 
                requestBuilder.setCloudProjectNumber(it)
            }

            // Suspend until the Play Services Task completes
            val integrityTokenResponse = integrityManager.requestIntegrityToken(requestBuilder.build()).await()
            val token = integrityTokenResponse.token()
            
            Log.d("PlayIntegrity", "Integrity token received successfully.")
            AttestationResult.Success(token)
            
        } catch (e: Exception) {
            handleException(e)
        }
    }

    /**
     * Centralized exception handling to provide clean Error states to the UI/ViewModel.
     */
    private fun handleException(e: Exception): AttestationResult.Error {
        Log.e("PlayIntegrity", "Failed to get integrity token", e)
        
        return if (e is IntegrityServiceException) {
            // IntegrityServiceException contains a specific Error Code mapping to Play Services issues
            // e.g., NO_PLAY_STORE, TOO_MANY_REQUESTS, NETWORK_ERROR, etc.
            val errorMessage = "Integrity API error (Code: ${e.errorCode}): ${e.message}"
            AttestationResult.Error(message = errorMessage, exception = e)
        } else {
            AttestationResult.Error(message = "An unexpected error occurred: ${e.localizedMessage}", exception = e)
        }
    }
}
